###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/memory_system/channel_mapper/impl/channel_mappers.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class CacheLineInterleave(Component):
    impl = "CacheLineInterleave"
    interleave_bits = Param(int, default=0)
