###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/memory_system/channel_mapper/impl/passthrough_channel_mapper.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component


class PassThroughChannelMapper(Component):
    impl = "PassThroughChannelMapper"
