###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Regenerate:   python -m ramulator codegen
###############################################################################
from .frfcfs import FRFCFS
from .frfcfs_row_hit import FRFCFSRowHit

__all__ = ['FRFCFS', 'FRFCFSRowHit']
