###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/scheduler/impl/frfcfs_rowhit.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component


class FRFCFSRowHit(Component):
    impl = "FRFCFS-RowHit"
