###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/plugin/impl/aqua.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class AQUA(Component):
    impl = "AQUA"
    num_art_entries = Param(int, required=True)
    num_fpt_entries = Param(int, required=True)
    num_qrows_per_bank = Param(int, required=True)
    art_threshold = Param(int, required=True)
    reset_period_ns = Param(int, default=64000000)
    debug = Param(bool, default=False)
