###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/plugin/impl/bin_trace_recorder.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class BinTraceRecorder(Component):
    impl = "BinTraceRecorder"
    path = Param(str, required=True)
    dram_type = Param(str, default='std::string(""')
