###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/plugin/impl/cmd_trace_recorder.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class CmdTraceRecorder(Component):
    impl = "CmdTraceRecorder"
    path = Param(str, required=True)
    binary = Param(bool, default=False)
