###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/plugin/impl/command_counter.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class CommandCounter(Component):
    impl = "CommandCounter"
    commands_to_count = Param(list, required=True)
    path = Param(str, required=True)
