###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/plugin/impl/graphene.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class Graphene(Component):
    impl = "Graphene"
    num_table_entries = Param(int, required=True)
    activation_threshold = Param(int, required=True)
    reset_period_ns = Param(int, required=True)
    debug = Param(bool, default=False)
