###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/plugin/impl/hydra.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class Hydra(Component):
    impl = "Hydra"
    hydra_tracking_threshold = Param(int, required=True)
    hydra_group_threshold = Param(int, required=True)
    hydra_row_group_size = Param(int, default=128)
    hydra_reset_period_ns = Param(int, default=64000000)
    hydra_rcc_num_per_rank = Param(int, default=4096)
    hydra_rcc_policy = Param(str, default='RANDOM')
    debug = Param(bool, default=False)
