###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/plugin/impl/hynix_trr.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class HynixTRR(Component):
    impl = "HynixTRR"
    sample_probability = Param(float, required=True)
    seed = Param(int, default=123)
