###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/plugin/impl/live_trace_streamer.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class LiveTraceStreamer(Component):
    impl = "LiveTraceStreamer"
    port = Param(int, default=3000)
    tick_interval = Param(int, default=10000)
    update_interval_s = Param(int, default=0.5)
    dram_type = Param(str, default='std::string(""')
