###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/plugin/impl/oracle_rh.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class OracleRH(Component):
    impl = "OracleRH"
    tRH = Param(int, required=True)
    debug = Param(bool, default=False)
