###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/plugin/impl/para.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class PARA(Component):
    impl = "PARA"
    threshold = Param(float, required=True)
    seed = Param(int, default=123)
    debug = Param(bool, default=False)
