###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/plugin/impl/rfm_manager.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class RFMManager(Component):
    impl = "RFMManager"
    rfm_thresh = Param(int, default=80)
