###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/plugin/impl/rrs.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class RRS(Component):
    impl = "RRS"
    num_hrt_entries = Param(int, required=True)
    num_rit_entries = Param(int, required=True)
    rss_threshold = Param(int, required=True)
    reset_period_ns = Param(int, default=64000000)
    debug = Param(bool, default=False)
