###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/plugin/impl/samsung_trr.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class SamsungTRR(Component):
    impl = "SamsungTRR"
    num_table_entries = Param(int, required=True)
    num_rows_per_rfm = Param(int, default=1)
