###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/plugin/impl/twice.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class TWiCeIdeal(Component):
    impl = "TWiCeIdeal"
    twice_rh_threshold = Param(int, required=True)
    twice_pruning_interval_threshold = Param(float, required=True)
    debug = Param(bool, default=False)
