/******************************************************************************
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by: python -m ramulator codegen
 * Source:       python/ramulator/dram/ddr3.py
 *
 * Regenerate:   python -m ramulator codegen DDR3
 ******************************************************************************/
#include "ramulator/dram/commands/ACT.h"
#include "ramulator/dram/commands/PREab.h"
#include "ramulator/dram/commands/PREpb.h"
#include "ramulator/dram/commands/RD.h"
#include "ramulator/dram/commands/RDA.h"
#include "ramulator/dram/commands/REFab.h"
#include "ramulator/dram/commands/WR.h"
#include "ramulator/dram/commands/WRA.h"
#include "ramulator/dram/commands/populate.h"
#include "ramulator/dram/dram_spec.h"

namespace Ramulator {

class DDR3 : public DRAMSpec {
 public:
  struct Level {
    enum : int { Channel, Rank, Bank, Row, Column, COUNT };
  };
  struct Command {
    enum : int { ACT, PREpb, PREab, RD, WR, RDA, WRA, REFab, COUNT };
  };
  struct State {
    enum : int { Opened, Closed, N_A, COUNT };
  };
  struct Timing {
    enum : int {
      rate,
      nBL,
      nCL,
      nRCD,
      nRP,
      nRAS,
      nRC,
      nWR,
      nRTP,
      nCWL,
      nCCD,
      nRRD,
      nWTR,
      nFAW,
      nRFC,
      nREFI,
      nCS,
      tCK_ps,
      COUNT
    };
  };

  using CommandImpls = std::tuple<Cmd::ACT<DDR3>, Cmd::PREpb<DDR3>, Cmd::PREab<DDR3>, Cmd::RD<DDR3>, Cmd::WR<DDR3>,
                                  Cmd::RDA<DDR3>, Cmd::WRA<DDR3>, Cmd::REFab<DDR3> >;

  DDR3(const ConfigNode& config) {
    // Counts
    level_count = Level::COUNT;
    command_count = Command::COUNT;
    state_count = State::COUNT;
    timing_count = Timing::COUNT;

    // String name maps + reverse lookup vectors
    set_names(levels, level_names, {"Channel", "Rank", "Bank", "Row", "Column"});
    set_names(commands, command_names, {"ACT", "PREpb", "PREab", "RD", "WR", "RDA", "WRA", "REFab"});
    set_names(states, state_names, {"Opened", "Closed", "N_A"});
    set_names(timings, timing_names,
              {"rate", "nBL", "nCL", "nRCD", "nRP", "nRAS", "nRC", "nWR", "nRTP", "nCWL", "nCCD", "nRRD", "nWTR",
               "nFAW", "nRFC", "nREFI", "nCS", "tCK_ps"});

    // Static spec data
    internal_prefetch_size = 8;
    init_states = {
        State::N_A,     // Channel
        State::N_A,     // Rank
        State::Closed,  // Bank
        State::Closed,  // Row
        State::N_A,     // Column
    };
    supported_requests = {
        Command::RD,  // Read -> RD
        Command::WR,  // Write -> WR
    };

    // Runtime config (organization, timing values, timing constraints)
    load_config(config);

    // Command handlers (function pointers, metadata, bank targets)
    populate_commands(CommandImpls{}, *this);
  }
};

// Self-registration
static bool _dram_ddr3 =
    DRAMSpec::register_standard("DDR3", [](const ConfigNode& config) { return std::make_unique<DDR3>(config); });

}  // namespace Ramulator
