/******************************************************************************
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by: python -m ramulator codegen
 * Source:       python/ramulator/dram/ddr5_vrr.py
 *
 * Regenerate:   python -m ramulator codegen DDR5_VRR
 ******************************************************************************/
#include "ramulator/dram/commands/ACT.h"
#include "ramulator/dram/commands/PREab.h"
#include "ramulator/dram/commands/PREpb.h"
#include "ramulator/dram/commands/RD.h"
#include "ramulator/dram/commands/RDA.h"
#include "ramulator/dram/commands/REFab.h"
#include "ramulator/dram/commands/VRR.h"
#include "ramulator/dram/commands/WR.h"
#include "ramulator/dram/commands/WRA.h"
#include "ramulator/dram/commands/populate.h"
#include "ramulator/dram/dram_spec.h"

namespace Ramulator {

class DDR5_VRR : public DRAMSpec {
 public:
  struct Level {
    enum : int { Channel, Rank, BankGroup, Bank, Row, Column, COUNT };
  };
  struct Command {
    enum : int { ACT, PREpb, PREab, RD, WR, RDA, WRA, REFab, VRR, COUNT };
  };
  struct State {
    enum : int { Opened, Closed, N_A, COUNT };
  };
  struct Timing {
    enum : int {
      rate,
      nBL,
      nCL,
      nRCD,
      nRP,
      nRAS,
      nRC,
      nWR,
      nRTP,
      nCWL,
      nPPD,
      nCCDS,
      nCCDL,
      nCCDS_WR,
      nCCDL_WR,
      nRRDS,
      nRRDL,
      nWTRS,
      nWTRL,
      nFAW,
      nRFC,
      nREFI,
      nCS,
      tCK_ps,
      nVRR,
      COUNT
    };
  };

  using CommandImpls =
      std::tuple<Cmd::ACT<DDR5_VRR>, Cmd::PREpb<DDR5_VRR>, Cmd::PREab<DDR5_VRR>, Cmd::RD<DDR5_VRR>, Cmd::WR<DDR5_VRR>,
                 Cmd::RDA<DDR5_VRR>, Cmd::WRA<DDR5_VRR>, Cmd::REFab<DDR5_VRR>, Cmd::VRR<DDR5_VRR> >;

  DDR5_VRR(const ConfigNode& config) {
    // Counts
    level_count = Level::COUNT;
    command_count = Command::COUNT;
    state_count = State::COUNT;
    timing_count = Timing::COUNT;

    // String name maps + reverse lookup vectors
    set_names(levels, level_names, {"Channel", "Rank", "BankGroup", "Bank", "Row", "Column"});
    set_names(commands, command_names, {"ACT", "PREpb", "PREab", "RD", "WR", "RDA", "WRA", "REFab", "VRR"});
    set_names(states, state_names, {"Opened", "Closed", "N_A"});
    set_names(timings, timing_names,
              {"rate",  "nBL",  "nCL",   "nRCD",  "nRP",      "nRAS",     "nRC",   "nWR",   "nRTP",
               "nCWL",  "nPPD", "nCCDS", "nCCDL", "nCCDS_WR", "nCCDL_WR", "nRRDS", "nRRDL", "nWTRS",
               "nWTRL", "nFAW", "nRFC",  "nREFI", "nCS",      "tCK_ps",   "nVRR"});

    // Static spec data
    internal_prefetch_size = 16;
    init_states = {
        State::N_A,     // Channel
        State::N_A,     // Rank
        State::N_A,     // BankGroup
        State::Closed,  // Bank
        State::Closed,  // Row
        State::N_A,     // Column
    };
    supported_requests = {
        Command::RD,  // Read -> RD
        Command::WR,  // Write -> WR
    };

    // Runtime config (organization, timing values, timing constraints)
    load_config(config);

    // Command handlers (function pointers, metadata, bank targets)
    populate_commands(CommandImpls{}, *this);
  }
};

// Self-registration
static bool _dram_ddr5_vrr = DRAMSpec::register_standard(
    "DDR5_VRR", [](const ConfigNode& config) { return std::make_unique<DDR5_VRR>(config); });

}  // namespace Ramulator
