/******************************************************************************
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by: python -m ramulator codegen
 * Source:       python/ramulator/dram/gddr7.py
 *
 * Regenerate:   python -m ramulator codegen GDDR7
 ******************************************************************************/
#include "ramulator/dram/commands/ACT.h"
#include "ramulator/dram/commands/PREab.h"
#include "ramulator/dram/commands/PREpb.h"
#include "ramulator/dram/commands/RCKSTOP.h"
#include "ramulator/dram/commands/RCKSTRT.h"
#include "ramulator/dram/commands/RD.h"
#include "ramulator/dram/commands/RDA.h"
#include "ramulator/dram/commands/REFab.h"
#include "ramulator/dram/commands/REFpb.h"
#include "ramulator/dram/commands/RFMab.h"
#include "ramulator/dram/commands/RFMpb.h"
#include "ramulator/dram/commands/WR.h"
#include "ramulator/dram/commands/WRA.h"
#include "ramulator/dram/commands/populate.h"
#include "ramulator/dram/dram_spec.h"

namespace Ramulator {

class GDDR7 : public DRAMSpec {
 public:
  struct Level {
    enum : int { Channel, Bank, Row, Column, COUNT };
  };
  struct Command {
    enum : int { ACT, PREpb, PREab, RD, WR, RDA, WRA, REFab, REFpb, RFMab, RFMpb, RCKSTRT, RCKSTOP, COUNT };
  };
  struct State {
    enum : int { Opened, Closed, N_A, COUNT };
  };
  struct Timing {
    enum : int {
      rate,
      nBL,
      nRL,
      nWL,
      nDQERL,
      nRCDRD,
      nRCDWR,
      nRP,
      nRAS,
      nRC,
      nRRD,
      nRREFD,
      nRPD,
      nRTPSB,
      nPPD,
      nWR,
      nCCD,
      nCCDSB,
      nWTR,
      nWTRSB,
      nRTW,
      nREFI,
      nREFIpb,
      nRFCab,
      nRFCpb,
      nRDREFab,
      nRFMab,
      nRFMpb,
      nRCKSTRT2RD,
      nRD2RCKSTOP,
      nRCKSP2ST,
      nRCKST2SP,
      nRCKSTOP_LAT,
      nRCKEN,
      nRCK_LS,
      nRCKPST,
      nRCK_HS,
      tCK_ps,
      COUNT
    };
  };

  using CommandImpls = std::tuple<Cmd::ACT<GDDR7>, Cmd::PREpb<GDDR7>, Cmd::PREab<GDDR7>, Cmd::RD<GDDR7>, Cmd::WR<GDDR7>,
                                  Cmd::RDA<GDDR7>, Cmd::WRA<GDDR7>, Cmd::REFab<GDDR7>, Cmd::REFpb<GDDR7>,
                                  Cmd::RFMab<GDDR7>, Cmd::RFMpb<GDDR7>, Cmd::RCKSTRT<GDDR7>, Cmd::RCKSTOP<GDDR7> >;

  GDDR7(const ConfigNode& config) {
    // Counts
    level_count = Level::COUNT;
    command_count = Command::COUNT;
    state_count = State::COUNT;
    timing_count = Timing::COUNT;

    // String name maps + reverse lookup vectors
    set_names(levels, level_names, {"Channel", "Bank", "Row", "Column"});
    set_names(
        commands, command_names,
        {"ACT", "PREpb", "PREab", "RD", "WR", "RDA", "WRA", "REFab", "REFpb", "RFMab", "RFMpb", "RCKSTRT", "RCKSTOP"});
    set_names(states, state_names, {"Opened", "Closed", "N_A"});
    set_names(timings, timing_names,
              {"rate",         "nBL",      "nRL",     "nWL",     "nDQERL",      "nRCDRD",      "nRCDWR",    "nRP",
               "nRAS",         "nRC",      "nRRD",    "nRREFD",  "nRPD",        "nRTPSB",      "nPPD",      "nWR",
               "nCCD",         "nCCDSB",   "nWTR",    "nWTRSB",  "nRTW",        "nREFI",       "nREFIpb",   "nRFCab",
               "nRFCpb",       "nRDREFab", "nRFMab",  "nRFMpb",  "nRCKSTRT2RD", "nRD2RCKSTOP", "nRCKSP2ST", "nRCKST2SP",
               "nRCKSTOP_LAT", "nRCKEN",   "nRCK_LS", "nRCKPST", "nRCK_HS",     "tCK_ps"});

    // Static spec data
    internal_prefetch_size = 32;
    init_states = {
        State::N_A,     // Channel
        State::Closed,  // Bank
        State::Closed,  // Row
        State::N_A,     // Column
    };
    supported_requests = {
        Command::RD,  // Read -> RD
        Command::WR,  // Write -> WR
    };

    // Runtime config (organization, timing values, timing constraints)
    load_config(config);

    // Command handlers (function pointers, metadata, bank targets)
    populate_commands(CommandImpls{}, *this);

    // Bus classification (for dual-bus controllers)
    command_meta[Command::ACT].is_row_command = true;
    command_meta[Command::PREpb].is_row_command = true;
    command_meta[Command::PREab].is_row_command = true;
    command_meta[Command::REFab].is_row_command = true;
    command_meta[Command::REFpb].is_row_command = true;
    command_meta[Command::RFMab].is_row_command = true;
    command_meta[Command::RFMpb].is_row_command = true;
    command_meta[Command::RD].is_column_command = true;
    command_meta[Command::WR].is_column_command = true;
    command_meta[Command::RDA].is_column_command = true;
    command_meta[Command::WRA].is_column_command = true;
    command_meta[Command::RCKSTRT].is_column_command = true;
    command_meta[Command::RCKSTOP].is_column_command = true;
  }
};

// Self-registration
static bool _dram_gddr7 =
    DRAMSpec::register_standard("GDDR7", [](const ConfigNode& config) { return std::make_unique<GDDR7>(config); });

}  // namespace Ramulator
