/******************************************************************************
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by: python -m ramulator codegen
 * Source:       python/ramulator/dram/gddr6.py
 *
 * Regenerate:   python -m ramulator codegen GDDR6
 ******************************************************************************/
#include "ramulator/dram/commands/ACT.h"
#include "ramulator/dram/commands/PREab.h"
#include "ramulator/dram/commands/PREpb.h"
#include "ramulator/dram/commands/RD.h"
#include "ramulator/dram/commands/RDA.h"
#include "ramulator/dram/commands/REFab.h"
#include "ramulator/dram/commands/REFpb.h"
#include "ramulator/dram/commands/WR.h"
#include "ramulator/dram/commands/WRA.h"
#include "ramulator/dram/commands/populate.h"
#include "ramulator/dram/dram_spec.h"

namespace Ramulator {

class GDDR6 : public DRAMSpec {
 public:
  struct Level {
    enum : int { Channel, BankGroup, Bank, Row, Column, COUNT };
  };
  struct Command {
    enum : int { ACT, PREab, PREpb, RD, WR, RDA, WRA, REFab, REFpb, COUNT };
  };
  struct State {
    enum : int { Opened, Closed, N_A, COUNT };
  };
  struct Timing {
    enum : int {
      rate,
      nBL,
      nCL,
      nRCDRD,
      nRCDWD,
      nRP,
      nRAS,
      nRC,
      nWR,
      nRTP,
      nCWL,
      nCCDS,
      nCCDL,
      nRRDS,
      nRRDL,
      nWTRS,
      nWTRL,
      nFAW,
      nRFC,
      nRFCpb,
      nRREFD,
      nREFI,
      tCK_ps,
      nRFCab,
      COUNT
    };
  };

  using CommandImpls = std::tuple<Cmd::ACT<GDDR6>, Cmd::PREab<GDDR6>, Cmd::PREpb<GDDR6>, Cmd::RD<GDDR6>, Cmd::WR<GDDR6>,
                                  Cmd::RDA<GDDR6>, Cmd::WRA<GDDR6>, Cmd::REFab<GDDR6>, Cmd::REFpb<GDDR6> >;

  GDDR6(const ConfigNode& config) {
    // Counts
    level_count = Level::COUNT;
    command_count = Command::COUNT;
    state_count = State::COUNT;
    timing_count = Timing::COUNT;

    // String name maps + reverse lookup vectors
    set_names(levels, level_names, {"Channel", "BankGroup", "Bank", "Row", "Column"});
    set_names(commands, command_names, {"ACT", "PREab", "PREpb", "RD", "WR", "RDA", "WRA", "REFab", "REFpb"});
    set_names(states, state_names, {"Opened", "Closed", "N_A"});
    set_names(timings, timing_names, {"rate",  "nBL",  "nCL",  "nRCDRD", "nRCDWD", "nRP",   "nRAS",   "nRC",
                                      "nWR",   "nRTP", "nCWL", "nCCDS",  "nCCDL",  "nRRDS", "nRRDL",  "nWTRS",
                                      "nWTRL", "nFAW", "nRFC", "nRFCpb", "nRREFD", "nREFI", "tCK_ps", "nRFCab"});

    // Static spec data
    internal_prefetch_size = 16;
    init_states = {
        State::N_A,     // Channel
        State::N_A,     // BankGroup
        State::Closed,  // Bank
        State::Closed,  // Row
        State::N_A,     // Column
    };
    supported_requests = {
        Command::RD,  // Read -> RD
        Command::WR,  // Write -> WR
    };

    // Runtime config (organization, timing values, timing constraints)
    load_config(config);

    // Command handlers (function pointers, metadata, bank targets)
    populate_commands(CommandImpls{}, *this);
  }
};

// Self-registration
static bool _dram_gddr6 =
    DRAMSpec::register_standard("GDDR6", [](const ConfigNode& config) { return std::make_unique<GDDR6>(config); });

}  // namespace Ramulator
