/******************************************************************************
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by: python -m ramulator codegen
 * Source:       python/ramulator/dram/hbm1.py
 *
 * Regenerate:   python -m ramulator codegen HBM1
 ******************************************************************************/
#include "ramulator/dram/commands/ACT.h"
#include "ramulator/dram/commands/PREab.h"
#include "ramulator/dram/commands/PREpb.h"
#include "ramulator/dram/commands/RD.h"
#include "ramulator/dram/commands/RDA.h"
#include "ramulator/dram/commands/REFab.h"
#include "ramulator/dram/commands/REFpb.h"
#include "ramulator/dram/commands/WR.h"
#include "ramulator/dram/commands/WRA.h"
#include "ramulator/dram/commands/populate.h"
#include "ramulator/dram/dram_spec.h"

namespace Ramulator {

class HBM1 : public DRAMSpec {
 public:
  struct Level {
    enum : int { Channel, BankGroup, Bank, Row, Column, COUNT };
  };
  struct Command {
    enum : int { ACT, PREpb, PREab, RD, WR, RDA, WRA, REFab, REFpb, COUNT };
  };
  struct State {
    enum : int { Opened, Closed, N_A, COUNT };
  };
  struct Timing {
    enum : int {
      rate,
      nBL,
      nCL,
      nRCDRD,
      nRCDWR,
      nRP,
      nRAS,
      nRC,
      nWR,
      nRTPL,
      nCWL,
      nCCDS,
      nCCDL,
      nRRDS,
      nRRDL,
      nWTRS,
      nWTRL,
      nFAW,
      nRFC,
      nRFCpb,
      nRREFD,
      nREFI,
      nREFIpb,
      tCK_ps,
      COUNT
    };
  };

  using CommandImpls = std::tuple<Cmd::ACT<HBM1>, Cmd::PREpb<HBM1>, Cmd::PREab<HBM1>, Cmd::RD<HBM1>, Cmd::WR<HBM1>,
                                  Cmd::RDA<HBM1>, Cmd::WRA<HBM1>, Cmd::REFab<HBM1>, Cmd::REFpb<HBM1> >;

  HBM1(const ConfigNode& config) {
    // Counts
    level_count = Level::COUNT;
    command_count = Command::COUNT;
    state_count = State::COUNT;
    timing_count = Timing::COUNT;

    // String name maps + reverse lookup vectors
    set_names(levels, level_names, {"Channel", "BankGroup", "Bank", "Row", "Column"});
    set_names(commands, command_names, {"ACT", "PREpb", "PREab", "RD", "WR", "RDA", "WRA", "REFab", "REFpb"});
    set_names(states, state_names, {"Opened", "Closed", "N_A"});
    set_names(timings, timing_names, {"rate",  "nBL",   "nCL",  "nRCDRD", "nRCDWR", "nRP",   "nRAS",    "nRC",
                                      "nWR",   "nRTPL", "nCWL", "nCCDS",  "nCCDL",  "nRRDS", "nRRDL",   "nWTRS",
                                      "nWTRL", "nFAW",  "nRFC", "nRFCpb", "nRREFD", "nREFI", "nREFIpb", "tCK_ps"});

    // Static spec data
    internal_prefetch_size = 2;
    init_states = {
        State::N_A,     // Channel
        State::N_A,     // BankGroup
        State::Closed,  // Bank
        State::Closed,  // Row
        State::N_A,     // Column
    };
    supported_requests = {
        Command::RD,  // Read -> RD
        Command::WR,  // Write -> WR
    };

    // Runtime config (organization, timing values, timing constraints)
    load_config(config);

    // Command handlers (function pointers, metadata, bank targets)
    populate_commands(CommandImpls{}, *this);

    // Bus classification (for dual-bus controllers)
    command_meta[Command::ACT].is_row_command = true;
    command_meta[Command::PREpb].is_row_command = true;
    command_meta[Command::PREab].is_row_command = true;
    command_meta[Command::REFab].is_row_command = true;
    command_meta[Command::REFpb].is_row_command = true;
    command_meta[Command::RD].is_column_command = true;
    command_meta[Command::WR].is_column_command = true;
    command_meta[Command::RDA].is_column_command = true;
    command_meta[Command::WRA].is_column_command = true;
  }
};

// Self-registration
static bool _dram_hbm1 =
    DRAMSpec::register_standard("HBM1", [](const ConfigNode& config) { return std::make_unique<HBM1>(config); });

}  // namespace Ramulator
