###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/addr_mapper/impl/ch_ra_ba_ro_co.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component


class ChRaBaRoCo(Component):
    impl = "ChRaBaRoCo"
