###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/addr_mapper/impl/direct_mapper.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component


class DirectMapper(Component):
    impl = "DirectMapper"
