###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/addr_mapper/impl/rit_addr_mapper.h
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param, Child


class RITAddrMapper(Component):
    impl = "RITAddrMapper"
    reserved_rows_per_bank = Param(int, default=0)
    addr_mapper = Child("addr_mapper")
