###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/addr_mapper/impl/ro_ba_ra_co_ch.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component


class RoBaRaCoCh(Component):
    impl = "RoBaRaCoCh"
