###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/impl/blockhammer_controller.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param, Child, ChildList


class BlockHammer(Component):
    impl = "BlockHammer"
    wr_low_watermark = Param(float, default=0.2)
    wr_high_watermark = Param(float, default=0.8)
    read_buffer_size = Param(int, default=32)
    write_buffer_size = Param(int, default=32)
    priority_buffer_size = Param(int, default=1568)
    bf_num_filters = Param(int, default=2)
    bf_len_epoch = Param(int, default=64000000)
    bf_ctr_count = Param(int, default=1024)
    bf_ctr_thresh = Param(int, default=128)
    bf_ctr_saturate = Param(bool, default=False)
    bf_num_hashes = Param(int, default=4)
    bf_hist_max_freq = Param(int, default=1)
    bf_num_rh = Param(int, default=16384)
    bf_trefw = Param(int, default=64000000)
    bf_trc = Param(int, default=75)
    debug = Param(bool, default=False)
    scheduler = Child("scheduler")
    refresh_manager = Child("refresh_manager")
    row_policy = Child("row_policy")
    addr_mapper = Child("addr_mapper")
    dram = Child("dram")
    controller_plugins = ChildList("controller_plugin")
