###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/impl/gddr7_controller.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param, Child, ChildList


class GDDR7(Component):
    impl = "GDDR7"
    wr_low_watermark = Param(float, default=0.2)
    wr_high_watermark = Param(float, default=0.8)
    read_buffer_size = Param(int, default=32)
    write_buffer_size = Param(int, default=32)
    priority_buffer_size = Param(int, default=1568)
    rck_mode = Param(str, default='always_on')
    scheduler = Child("scheduler")
    refresh_manager = Child("refresh_manager")
    row_policy = Child("row_policy")
    addr_mapper = Child("addr_mapper")
    dram = Child("dram")
    controller_plugins = ChildList("controller_plugin")
