###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/impl/prac_controller.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param, Child, ChildList


class PRAC(Component):
    impl = "PRAC"
    wr_low_watermark = Param(float, default=0.2)
    wr_high_watermark = Param(float, default=0.8)
    read_buffer_size = Param(int, default=32)
    write_buffer_size = Param(int, default=32)
    priority_buffer_size = Param(int, default=1568)
    abo_threshold = Param(int, default=512)
    abo_act_ns = Param(int, default=180)
    abo_recovery_refs = Param(int, default=4)
    abo_delay_acts = Param(int, default=4)
    debug = Param(bool, default=False)
    scheduler = Child("scheduler")
    refresh_manager = Child("refresh_manager")
    row_policy = Child("row_policy")
    addr_mapper = Child("addr_mapper")
    dram = Child("dram")
    controller_plugins = ChildList("controller_plugin")
