###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Regenerate:   python -m ramulator codegen
###############################################################################
from .no_translation import NoTranslation

__all__ = ['NoTranslation']
