###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/translation/impl/no_translation.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class NoTranslation(Component):
    impl = "NoTranslation"
    max_addr = Param(int, required=True, cpp_type="Addr_t")
