###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Regenerate:   python -m ramulator codegen
###############################################################################
from .external import External
from .latency_throughput_trace import LatencyThroughputTrace
from .load_store_trace import LoadStoreTrace
from .read_write_trace import ReadWriteTrace
from .simple_o3 import SimpleO3

__all__ = ['External', 'LatencyThroughputTrace', 'LoadStoreTrace', 'ReadWriteTrace', 'SimpleO3']
