###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/frontend/impl/processor/bhO3/bhO3.h
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param, Child


class BHO3(Component):
    impl = "BHO3"
    clock_ratio = Param(int, required=True, cpp_type="unsigned int")
    num_expected_insts = Param(int, required=True)
    num_max_cycles = Param(int, default=0, cpp_type="uint64_t")
    traces = Param(list, required=True)
    ipc = Param(int, default=4)
    inst_window_depth = Param(int, default=128)
    llc_latency = Param(int, default=47)
    llc_linesize = Param(int, default=64)
    llc_associativity = Param(int, default=8)
    llc_capacity_per_core = Param(str, default='2MB')
    llc_num_mshr_per_core = Param(int, default=16)
    lat_hist_sens = Param(int, default=0)
    dump_path = Param(str, default='')
    attacker_core_ids = Param(list, default=[], cpp_type="std::vector<int>")
    translation = Child("translation")
