###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/frontend/impl/memory_trace/latency_throughput_trace.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class LatencyThroughputTrace(Component):
    impl = "LatencyThroughputTrace"
    clock_ratio = Param(int, required=True, cpp_type="unsigned int")
    nop_counter = Param(int, required=True)
    num_probe_requests = Param(int, default=0)
    latency_measure_mode = Param(str, default='random-probe')
    latency_sample_count = Param(int, default=0)
    streaming_only = Param(bool, default=False)
    num_streaming_requests = Param(int, default=0)
    stream_cls = Param(int, default=8)
    stagger_stream_rows = Param(bool, default=False)
    warmup_cycles = Param(int, default=10000)
    read_ratio = Param(int, default=100)
    seed = Param(int, default=12345, cpp_type="uint64_t")
    addr_vec_size = Param(int, required=True)
    total_bank_units = Param(int, required=True)
    row_pos = Param(int, required=True)
    col_pos = Param(int, required=True)
    num_rows = Param(int, required=True)
    num_cols = Param(int, required=True)
    internal_prefetch_size = Param(int, required=True)
    num_cls = Param(int, required=True)
    bank_positions = Param(list, required=True, cpp_type="std::vector<int>")
    bank_counts = Param(list, required=True, cpp_type="std::vector<int>")
