###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/refresh/impl/all_bank.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class AllBank(Component):
    impl = "AllBank"
    scatter_interval = Param(int, default=0)
    debug = Param(bool, default=False)
