###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/memory_system/impl/generic_dram_system.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param, Child, ChildList


class GenericDRAM(Component):
    impl = "GenericDRAM"
    clock_ratio = Param(int, required=True, cpp_type="unsigned int")
    channel_mapper = Child("channel_mapper")
    controllers = ChildList("controller")
