###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Regenerate:   python -m ramulator codegen
###############################################################################
from .closed_cap import ClosedCAP
from .open import Open

__all__ = ['ClosedCAP', 'Open']
