###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/rowpolicy/impl/closed_cap.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class ClosedCAP(Component):
    impl = "ClosedCAP"
    cap = Param(int, default=4)
