###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Regenerate:   python -m ramulator codegen
###############################################################################
"""Ramulator2 — cycle-accurate DRAM simulator with Python bindings."""

from ramulator.components import Component

# Interface-based namespaces — each subpackage = one C++ interface
from ramulator import dram
from ramulator import addr_mapper
from ramulator import channel_mapper
from ramulator import controller
from ramulator import controller_plugin
from ramulator import frontend
from ramulator import memory_system
from ramulator import refresh_manager
from ramulator import row_policy
from ramulator import scheduler
from ramulator import translation

# Hand-written integration modules
from ramulator import gem5


class Simulation:
    """Run a Ramulator2 simulation from Python component objects or raw dicts."""

    def __init__(self, frontend, memory_system):
        from ramulator._ramulator import Simulation as _CppSimulation

        fe_config = frontend.to_config() if isinstance(frontend, Component) else frontend
        ms_config = (
            memory_system.to_config() if isinstance(memory_system, Component) else memory_system
        )

        # Build the top-level config dict expected by C++
        config = {
            "frontend": fe_config,
            "memory_system": ms_config,
        }
        self._sim = _CppSimulation(config)

    def run(self):
        """Run the simulation to completion."""
        self._sim.run()

    def finalize(self):
        """Finalize the simulation and flush final outputs."""
        self._sim.finalize()

    @property
    def stats(self):
        """Update derived stats and return a nested dict snapshot."""
        return self._sim.get_stats()

    @property
    def stats_yaml(self):
        """Update derived stats and return a YAML-formatted snapshot."""
        return self._sim.get_stats_yaml()


__all__ = ['dram', 'addr_mapper', 'channel_mapper', 'controller', 'controller_plugin', 'frontend', 'memory_system', 'refresh_manager', 'row_policy', 'scheduler', 'translation', 'gem5', 'Simulation']
